### ISSUE TITLE
webpack-dev-server fails to start on React Native 0.12/master

### ISSUE THREAD

**Issue by jsierles** [mjohnston/react-native-webpack-server#90] opened 2015-09-30 16:37 UTC
On the latest RN master, webpack-dev-server hangs without any debug info. Not sure of the best way to get more information about this. Here's what the console looks like:

```
MacBook-Air:BabelES6 joshua$ npm start

> BabelES6@0.0.2 start /Users/joshua/code/react-native-webpack-server/Examples/BabelES6
> react-native-webpack-server start

Server listening at http://localhost:8080
```

**Comment by elliottsj** [comment] 2015-10-01 02:30
I'm not able to reproduce this. Did you make sure to `npm install` after pulling master?

**Comment by elliottsj** [comment] 2015-10-01 02:31
Oh wait, RN 0.12. I haven't done much testing with 0.12 yet; it's on my todo list :smile:

**Comment by jsierles** [comment] 2015-10-02 09:48
Great! Is there a way to enable debug logging?

**Comment by elliottsj** [comment] 2015-10-03 15:58
Sorry, there's no debug logging yet. Can you try out the `rn-0.12` branch? I wasn't able to reproduce your hanging issue, but hopefully the the changes I made fix your issue.

**Comment by jsierles** [comment] 2015-10-03 19:18
This still happens for me with the 0.12 branch. Which npm and node are you on? I'm on node 4.1.1 and npm 2.14.4.

**Comment by elliottsj** [comment] 2015-10-03 19:42
I'm using the same versions. Have you tried `npm install` in the BabelES6
directory?

**Comment by codecvlt** [comment] 2015-10-24 23:49
I'm getting this same issue as well. Just updated to RN 13.1

**Comment by bluedaniel** [comment] 2015-10-25 20:21
I'm having this issue too with the latest RN 13.1

**Comment by tmitchel2** [comment] 2015-10-27 16:39
I'm having this issue too with the latest RN 13.2

**Comment by tmitchel2** [comment] 2015-10-27 16:49
Can confirm that this seems to have been fixed on this fork https://github.com/jhabdas/react-native-webpack-server

**Comment by elliottsj** [comment] 2015-10-29 02:09
Added RN 0.13 support here: #117. RN 0.12 should work as well. Please try out the `rn-0.13 branch` if you can!

**Closed as completed** 2015-10-30 22:29 UTC
